### ISSUE TITLE
Could not find package theorythree/laratoaste

### ISSUE THREAD

**Issue by WitekS** [theorythree/LaraToaster#1]
`composer require theorythree/laratoaster

  [InvalidArgumentException]
  Could not find package theorythree/laratoaster.

  Did you mean this?
      theorythree/laratoaster`

**Comment by dmerfeld** [comment]
Thank you for submitting this issue. 

You can now use `composer require theorythree/laratoaster` to install the package. Also, we've updated the README.md with more examples and information on how to use the package.

Happy coding!
