### ISSUE TITLE
double messages

### ISSUE THREAD

**Issue by WitekS** [theorythree/LaraToaster#2]
## Detailed description

after going to the site where there were no messages set up, however, they are displayed again, this is probably due to data stored in the sessja for flash once it is as new and then as old below the screenshot from the session:

first
`array(13) { ["_flash"]=> array(2) { ["old"]=> array(0) { } ["new"]=> array(8) { [0]=> string(7) "success" [1]=> string(7) "warning" [2]=> string(6) "danger" [3]=> string(5) "white" [4]=> string(5) "black" [5]=> string(5) "light" [6]=> string(4) "dark" [7]=> string(4) "info" } } ["_token"]=> string(40) "unNl6ZqhaMT5qw0eE6261WEk4iVFHBC80AmBQQRo" ["url"]=> array(0) { } ["_previous"]=> array(1) { ["url"]=> string(17) "http://l5app/home" } ["login_web_59ba36addc2b2f9401580f014c7f58ea4e30989d"]=> int(1) ["success"]=> string(21) "1.Success feels good!" ["warning"]=> string(31) "2.I got bad feeling about this." ["danger"]=> string(42) "3.I imagined that working out differently." ["white"]=> string(43) "4.I don't see the world in black and white." ["black"]=> string(28) "5.Who turned out the lights?" ["light"]=> string(49) "6.I probably should be used on a dark background." ["dark"]=> string(50) "7.I probably should be used on a light background." ["info"]=> string(22) "8.I'm cool either way." }`
two
`array(13) { ["_flash"]=> array(2) { ["old"]=> array(8) { [0]=> string(7) "success" [1]=> string(7) "warning" [2]=> string(6) "danger" [3]=> string(5) "white" [4]=> string(5) "black" [5]=> string(5) "light" [6]=> string(4) "dark" [7]=> string(4) "info" } ["new"]=> array(0) { } } ["_token"]=> string(40) "unNl6ZqhaMT5qw0eE6261WEk4iVFHBC80AmBQQRo" ["url"]=> array(0) { } ["_previous"]=> array(1) { ["url"]=> string(17) "http://l5app/home" } ["login_web_59ba36addc2b2f9401580f014c7f58ea4e30989d"]=> int(1) ["success"]=> string(21) "1.Success feels good!" ["warning"]=> string(31) "2.I got bad feeling about this." ["danger"]=> string(42) "3.I imagined that working out differently." ["white"]=> string(43) "4.I don't see the world in black and white." ["black"]=> string(28) "5.Who turned out the lights?" ["light"]=> string(49) "6.I probably should be used on a dark background." ["dark"]=> string(50) "7.I probably should be used on a light background." ["info"]=> string(22) "8.I'm cool either way." }`

**Comment by dmerfeld** [comment]
Thank you. We'll look into this issue.

**Comment by dmerfeld** [comment]
We were able to replicate this issue. A fix will be in place for the next release.
